### PR TITLE
 Issue-20 Created a html code for login page

### PR DESCRIPTION
**Pull request by SeshaphaniGrandhe**

### CODE REVIEW

**Review by PoojithaKamana — CHANGES_REQUESTED** [review]
When I tried to run the code it shows an error in url step. Can you please check the url format and correct it.

**Review by Thammak — CHANGES_REQUESTED** [review]
Can you please change url format in line 21 as well.

**Review by PoojithaKamana — APPROVED** [review]
Everything looks good now.

**Review by Thammak — APPROVED** [review]
Now there is no error and the code looks perfect.

**Pull request merged**
