### PR TITLE
Issue-21 Created dashboard page using html code

### PR DESCRIPTION
**Pull request by PoojithaKamana**

### CODE REVIEW

**Review by Thammak — CHANGES_REQUESTED** [review]
I think you missed to import the CSS file in the html code. Please check again and make changes.

**Comment by PoojithaKamana** [comment]
I imported css file in the html code successfully. Please review it  once again.

**Review by Thammak — APPROVED** [review]
I reviewed this code and it works well.

**Review by SeshaphaniGrandhe — CHANGES_REQUESTED** [review]
Everything looks good but Can you add  more instructions to the code and add a numbers to the each step instructions. So, user will get more idea about the quizz.

**Review by SeshaphaniGrandhe — APPROVED** [review]
Looks goods.

**Review by ankithreddygodala — CHANGES_REQUESTED** [review]
You missed the closing headers to the file. Please check again.

**Review by ankithreddygodala — APPROVED** [review]
I have executed the code and it runs perfectly.

**Review by Mohanakavyac — APPROVED** [review]
The html code of Dashboard looks good and it is easy to use and understand by the users.

**Pull request closed without merging**
